APIVersion: "1"
name: sprint-[ts]
type: drupal8
docroot: drupal8
php_version: "7.2"
router_http_port: "8080"
router_https_port: "8443"
provider: default

# Certain ddev commands can be extended to run tasks before or after the ddev
# command is executed.
# See https://ddev.readthedocs.io/en/latest/users/extending-commands/ for more
# information on the commands that can be extended and the tasks you can define
# for them.
# hooks:
#   post-import-db:
#     - exec: "drush cr"
